
HTTP:
  server:
    host: 127.0.0.1
    port:
      - 8080
      - 8081
    index: index.html
    root: /var/www/html
  server:
    host: 127.0.0.1
    port:
      - 8082
      - 8083
    index: index.htm
    root: /users/ndahib/Desktop/c
    location:
      - path: /test
      - index: index.html
      - root: /var/www/html

error_page: /error404.html
include:  "Yaml/Login.yaml"