http:
  server:
    host: 127.0.0.1
    port:
      - 8080
      - 8081
    index: index.html
    root: /var/www/html
  server:
    host: 127.0.0.1
    port:
      - 8082
      - 8083
    index: index.htm
    root: /users/ndahib/Desktop/c
    location:
      - path: /test
      - index: index.html
      - root: /var/www/html

global:
  - allowedMethods: GET,POST
  - clientMaxBodySize: 100M
  - errorPage:
    - 404: /error404.html
    - 500: /error500.html
    - 503: /error503.html
    - 504: /error504.html
include:  "Yaml/Login.yaml"